apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kubeflow
data:
  credentials: |-
    {
       "s3": {
           "s3AccessKeyIDName": "accesskey",
           "s3SecretAccessKeyName": "secretkey"
       }
    }
